apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: pftnamespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: matejgorjanov201536/personal_finance_tracker:frontend
        imagePullPolicy: Never
        env:
        - name: EXT_PUBLIC_API_URL
          value: http://localhost/api
        ports:
        - containerPort: 3000
          protocol: TCP
