apiVersion: v1
kind: PersistentVolume
metadata:
  name: devopsproject-mysql-pv
  namespace: pftnamespace
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: C:/Users/Asus/Desktop/DevOps Project/db/init 
