apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devopsproject-mysql-pvc
  namespace: pftnamespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
